# Generated by Django 4.2 on 2023-04-28 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolists', '0004_todolist_completed_at_todolist_updated_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='completed_at',
            new_name='completion_at',
        ),
    ]
